// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DatabaseFirst.Models
{
    public partial class TestPrdResult
    {
        public int ProductID { get; set; }
        public short? UnitsinStock { get; set; }
    }
}
